In [2]:
!pip install pandas
!pip install ultralytics
!pip install openpyxl


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from ultralytics import YOLO
import pandas as pd
import os

# Yolo를 부르는법

In [3]:
model=YOLO()
model.predict('img\img.jpg')


image 1/1 d:\GitHub\Yolov8\detect\img\img.jpg: 608x640 10 persons, 136.4ms
Speed: 5.7ms preprocess, 136.4ms inference, 7.9ms postprocess per image at shape (1, 3, 608, 640)


[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted p

# Yolo 예측하기

In [4]:
model.predict('img\img.jpg',save=True)


image 1/1 d:\GitHub\Yolov8\detect\img\img.jpg: 608x640 10 persons, 91.2ms
Speed: 3.1ms preprocess, 91.2ms inference, 0.9ms postprocess per image at shape (1, 3, 608, 640)
Results saved to runs\detect\predict2


[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted p

In [3]:
result=model.predict('img\img.jpg')
result


image 1/1 d:\GitHub\Yolov8\detect\img\img.jpg: 608x640 10 persons, 153.1ms
Speed: 8.7ms preprocess, 153.1ms inference, 1.5ms postprocess per image at shape (1, 3, 608, 640)


[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted p

In [7]:
result=result[0]
result

ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant',

In [13]:
boxes=result.boxes
boxes

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
conf: tensor([0.9373, 0.9168, 0.9045, 0.8898, 0.8857, 0.8522, 0.8273, 0.8257, 0.6037, 0.6022])
data: tensor([[9.5639e+02, 6.3733e+00, 1.2751e+03, 3.9475e+02, 9.3727e-01, 0.0000e+00],
        [4.8773e-01, 5.9597e+00, 3.2042e+02, 3.9324e+02, 9.1679e-01, 0.0000e+00],
        [3.2647e+02, 5.7630e+00, 6.3799e+02, 3.9507e+02, 9.0451e-01, 0.0000e+00],
        [6.3067e+02, 5.0023e+00, 9.5725e+02, 3.9340e+02, 8.8978e-01, 0.0000e+00],
        [9.5715e+02, 8.1493e+02, 1.2748e+03, 1.1908e+03, 8.8569e-01, 0.0000e+00],
        [3.7827e+02, 8.1468e+02, 5.9914e+02, 1.1873e+03, 8.5217e-01, 0.0000e+00],
        [9.8496e+02, 4.1631e+02, 1.2513e+03, 7.9353e+02, 8.2734e-01, 0.0000e+00],
        [4.5490e+01, 8.0906e+02, 2.7414e+02, 1.1923e+03, 8.2572e-01, 0.0000e+00],
        [7.7836e+01, 4.2611e+02, 2.6825e+02, 7.6559e+02, 6.0375e-01, 0.0000e+00],
        [6.4393e+02, 8.0759e+02, 9.5282e+02, 1.19

# cls는 탐지된 객체의 번호다

In [14]:
boxes.cls

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 확률

In [17]:
boxes.conf

tensor([0.9373, 0.9168, 0.9045, 0.8898, 0.8857, 0.8522, 0.8273, 0.8257, 0.6037, 0.6022])

# 박스친 위치

In [18]:
boxes.xyxy

tensor([[9.5639e+02, 6.3733e+00, 1.2751e+03, 3.9475e+02],
        [4.8773e-01, 5.9597e+00, 3.2042e+02, 3.9324e+02],
        [3.2647e+02, 5.7630e+00, 6.3799e+02, 3.9507e+02],
        [6.3067e+02, 5.0023e+00, 9.5725e+02, 3.9340e+02],
        [9.5715e+02, 8.1493e+02, 1.2748e+03, 1.1908e+03],
        [3.7827e+02, 8.1468e+02, 5.9914e+02, 1.1873e+03],
        [9.8496e+02, 4.1631e+02, 1.2513e+03, 7.9353e+02],
        [4.5490e+01, 8.0906e+02, 2.7414e+02, 1.1923e+03],
        [7.7836e+01, 4.2611e+02, 2.6825e+02, 7.6559e+02],
        [6.4393e+02, 8.0759e+02, 9.5282e+02, 1.1927e+03]])

# 내가 만든 함수

In [19]:
# 엑셀표로 변환
def PredictToPandas(img_path, model,save_path=None):
    result = model.predict(img_path)
    if not result:
        return pd.DataFrame(columns=["xmin", "ymin", "xmax", "ymax", "conf", "cls", "name"])
    
    boxes = result[0].boxes
    xyxy = boxes.xyxy.cpu().numpy()
    cls = boxes.cls.cpu().numpy()
    conf = boxes.conf.cpu().numpy()
    df=pd.DataFrame({
        "xmin": xyxy[:, 0],
        "ymin": xyxy[:, 1],
        "xmax": xyxy[:, 2],
        "ymax": xyxy[:, 3],
        "conf": conf,
        "cls": cls,
        "name": [model.names[int(i)] for i in cls]
    })
    
    if save_path:
        os.makedirs('result', exist_ok=True)
        save_path=os.path.join('result', save_path)
        if save_path.endswith(".csv"):
            df.to_csv(save_path, index=False)
        elif save_path.endswith(".json"):
            df.to_json(save_path, orient="records", indent=4)
        elif save_path.endswith(".xlsx"):
            df.to_excel(save_path, index=False)
        else:
            print("Unsupported file format. Use .csv, .json, or .xlsx")
    return df

In [20]:
PredictToPandas('img\muder.jpg',model)


image 1/1 d:\GitHub\Yolov8\detect\img\muder.jpg: 640x640 1 person, 1 scissors, 155.7ms
Speed: 9.5ms preprocess, 155.7ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)


xmin        ymin         xmax        ymax      conf   cls      name
0  298.764252    0.371289  1022.337219  994.979858  0.787023   0.0    person
1  308.218170  346.534485   756.365723  917.523315  0.429184  76.0  scissors

In [21]:
df=PredictToPandas('img\muder1.jpg',model)
df


image 1/1 d:\GitHub\Yolov8\detect\img\muder1.jpg: 640x640 2 persons, 1 knife, 1 scissors, 175.8ms
Speed: 7.1ms preprocess, 175.8ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)


xmin        ymin         xmax         ymax      conf   cls      name
0  331.040039    0.019727  1022.281372  1020.177917  0.385402   0.0    person
1  408.363831  616.659058   437.935730   726.174683  0.345758   0.0    person
2  514.876343  548.515442   820.103821   885.892395  0.328198  43.0     knife
3  515.508911  554.779785   820.507141   886.628906  0.267664  76.0  scissors

In [22]:
df[df['conf']>0.3]

xmin        ymin         xmax         ymax      conf   cls    name
0  331.040039    0.019727  1022.281372  1020.177917  0.385402   0.0  person
1  408.363831  616.659058   437.935730   726.174683  0.345758   0.0  person
2  514.876343  548.515442   820.103821   885.892395  0.328198  43.0   knife

In [12]:
model.predict('img\muder1.jpg',classes=[43,76.0])


image 1/1 d:\GitHub\Yolov8\detect\img\muder1.jpg: 640x640 1 knife, 1 scissors, 126.0ms
Speed: 7.8ms preprocess, 126.0ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)


[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted p